---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: trailing-whitespace
            exclude_types: [csv, json]
          # - id: flake8
    - repo: https://github.com/Madoshakalaka/pipenv-setup
      rev: v3.2.0
      hooks:
          - id: pipenv-setup
            args: [--dev, --pipfile]
            additional_dependencies:
                - vistir==0.6.1
                - black

    - repo: https://github.com/ambv/black
      rev: 22.10.0
      hooks:
          - id: black
