name: Type Check

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev

env:
    ACTIONS_RUNNER_DEBUG: ${{ vars.ACTIONS_RUNNER_DEBUG }}
    ACTIONS_STEP_DEBUG: ${{ vars.ACTIONS_STEP_DEBUG }}

jobs:
    typecheck:
        name: Type Check
        runs-on: ubuntu-latest

        steps:
            - name: Setup Python Environment
              uses: ./.github/workflows/setup-python.yml
              with:
                  python-version: "3.11"
                  cache-key: "mypy"

            - name: Run mypy
              run: |
                  source ${{ needs.setup.outputs.venv-path }}/bin/activate
                  mypy .
